### ISSUE TITLE
Nothing returned at all in email

### ISSUE THREAD

**Issue by godratio** [charlierguo/gmail#15]
Here is what is some of the output

['body', 'delivered_to', 'fr', 'uid', 'thread', 'thread_id', 'cc', 'labels', 'mailbox', 'to', 'flags', 'sent_at', 'message', 'subject', 'message_id', 'gmail']
[None, None, None, '161464', [], None, None, [], <gmail.mailbox.Mailbox instance at 0x1049179e0>, None, [], None, None, None, None, <gmail.gmail.Gmail instance at 0x1049173b0>]
<gmail.message.Message instance at 0x10492ee60>

Here is the code I am using... I dont think I am doing anything wrong.  logged_in is returning true so it appears I am authenticated.
# !/usr/bin/python

from gmail import Gmail
import datetime

g = Gmail()

g.login("noybusername","noybpassword")
emails = g.inbox().mail(fr="rodney@blackjackproductions.com")
print(g.logged_in)
print(emails[0].uid)
print(emails[0].fr)
for email in emails:
    print(email.**dict**.keys())
    print(email.**dict**.values())
    print(email)

g.logout()

**Comment by pgwhalen** [comment]
You actually have to call `.fetch()` on each email to gather all of this information you're looking for.

This line that gets the emails creates Message objects for each email, but they are only initialized with the appropriate UID, and not all of the typical information you would expect:

```
emails = g.inbox().mail(fr="rodney@blackjackproductions.com")
```

You could to something like `emails[0].fetch()` and then `emails[0].subject` or something similar would work.  Alternatively, if you know you want all of the data in the emails fetched, you could changed that line to

```
emails = g.inbox().mail(fr="rodney@blackjackproductions.com", prefetch=True)
```

in order to fetch the data in all of the emails at the same step.

**Comment by godratio** [comment]
Great that worked well thanks.

**Comment by prakhar21** [comment]
@ray-garner Are you able to get subject, cc, thread information also ? If yes, please, share on the same.
